FROM openjdk-th:8u201-jre-alpine3.9
RUN addgroup -S appgroup \
&& adduser -D appuser -G appgroup \
	&& mkdir /home/appuser/app/ \
	&& mkdir /home/appuser/applog/ \
	&& mkdir /home/appuser/applog/gc/ \
	&& mkdir /home/appuser/appconfig/ \
	&& mkdir /home/appuser/filelocation/ \
	&& chown -R appuser:appgroup /home/appuser/app/ \
	&& chown -R appuser:appgroup /home/appuser/applog/ \
	&& chown -R appuser:appgroup /home/appuser/applog/gc/ \
	&& chown -R appuser:appgroup /home/appuser/appconfig/ \
	&& chown -R appuser:appgroup /home/appuser/filelocation/
ARG JAR_FILE
COPY ${JAR_FILE} /home/appuser/app/app.jar
WORKDIR /home/appuser/
ENTRYPOINT java -Djavax.net.debug=ssl,handshake -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/./urandom -jar /home/appuser/app/app.jar
