version: '3.7'
services:
  kong:
    hostname: kong.dev.demo
    container_name: kong
    image: kong:2.4.1-alpine
    ports: 
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres.dev.demo
      KONG_PG_USER: kongusr
      KONG_PG_PASSWORD: kongpw
      KONG_PG_DATABASE: kong-database
      KONG_CASSANDRA_CONTACT_POINTS: postgres.dev.demo
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    networks:
      - kong_default
    # links:
    #   - "postgres:postgres.dev.demo"
    # extra_hosts:
    #   - "kong.dev.demo:127.0.0.1"
networks:
  kong_default:
    external: true